### ISSUE TITLE
unable to download via proxy

### ISSUE THREAD

**Issue by clydzik** [alexcojocaru/elasticsearch-maven-plugin#102]
In my environment via VPN there is proxy setup specified in maven settings.
When i run 'mvn test' and mvn elastic plugin want to try to download elastic
via url:
 https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-oss-7.1.0-windows-x86_64.zip to C:\Users\kxsgtq\AppData\Local\Temp\elasticsearch-oss-7.1.0-windows-x86_64.zip

When working without VPN the above is downloaded and put into local .m2 directory
Now this fails.
I suspect there should be a way to pass the proxy somehow.
maven itself use settings.xml but this seems not be applied

**Comment by alexcojocaru** [comment]
You have 2 options to work around this problem:

1. Manually download the ES package on the local machine, then set the `downloadUrl` property on the plugin configuration to its file location; on Linux is something like `file:///home/username/...` if I recall correctly, cannot say how it looks like on Windows.
This option is hacky, for you'd end up with a custom change to the pom.xml for it to work locally.

2. Here's how the plugin works: it checks if the artifact exists in the local maven repo and, if it doesn't, it downloads it from the default location (or the `downloadUrl` if provided) and installs it in the local repo. You can manually download the package and manually install it (maven can do that easily) in your local repo. 
For more details on the package resolution / installation, and the package coordinates, see https://github.com/alexcojocaru/elasticsearch-maven-plugin/blob/589e866cdef5195ddc35fb1f0a364661b5ab298e/src/main/java/com/github/alexcojocaru/mojo/elasticsearch/v2/step/ResolveElasticsearchStep.java#L59

for ES 7+, the package coordinates are:
groupId: com.github.alexcojocaru
artifactId: elasticsearch-oss
artifact type: zip

**Comment by clydzik** [comment]
yes. for now i put artifact into maven repos of our nexus and this is fine.
But tried somehow to specify the proxies to be used by by the above code. But for now did not find anything working.

**Comment by alexcojocaru** [comment]
Since the plugin runs in the same process as maven, I wonder if it's able to read the proxy related system properties (which I hope Maven set on start up): `http.proxySet`, `http.proxyHost` and `http.proxyPort`. Can you verify that?
If those properties are available, I could modify the `downloadArtifact` method in ResolveElasticsearchStep to use them.

**Comment by alexcojocaru** [comment]
Do you have any updates on this?

**Comment by clydzik** [comment]
Hello. Sorry. Since i had workaround i forgot to dig into that.

Now when analyzing a bit more and do like here:
https://medium.com/@petehouston/execute-maven-behind-a-corporate-proxy-network-5e08d075f744
It seems to be working.
I think probably last time i tried with env properties and some ide settings but forgot simply try commandline.

So when i pass 

mvn test -Dhttp.proxyHost=[...] -Dhttp.proxyPort=[...] -Dhttps.proxyHost=[...] -Dhttps.proxyPort=[...]

it works.
This is sufficient now for users i think
