### ISSUE TITLE
No such file or directory error during parallel plugin executions in jenkins

### ISSUE THREAD

**Issue by HighstreetHerbert** [alexcojocaru/elasticsearch-maven-plugin#105]
Propably the downloaded file in "/tmp/elasticsearch-oss-6.4.3.zip" is removed by one instance unexpected by the other instance. 

[ERROR] Failed to execute goal com.github.alexcojocaru:elasticsearch-maven-plugin:6.14:runforked (start-elasticsearch) on project sdnr-wt-common: com.github.alexcojocaru.mojo.elasticsearch.v2.configuration.ArtifactException: Failed to install artifact com.github.alexcojocaru:elasticsearch-oss:zip:6.4.3: /tmp/elasticsearch-oss-6.4.3.zip (No such file or directory) -> [Help 1]

Possible improvements:
  - Configurable tmp directory
  - download into target

**Comment by alexcojocaru** [comment]
Thanks for describing the problem and several potential solutions, but it is not clear to me how the parallel execution of your tests fails because of the plugin execution. The plugin is supposed to run only once in the *pre-integration-test* phase of the build, when the context for the integration tests is being set up. The ITs should execute in a subsequent phase (eg. *integration-test*), thus not conflicting with the ES archive download and ES startup.

**Comment by HighstreetHerbert** [comment]
We are using the plugin in our jenkins build that includes about 10 bundles.  4 Of them are using the plugin for junit test. The Jenkins uses a build server, that does the build for the 10 bundles in parallel. Because the plugin uses the same /tmp directory for all of the builds. The plugins are running all on this one /tmp directory for the same ES-ZIP file and the errors the we see are indicating such conflicts. E.g. one bundle stats "ES ZIP file not existing". If we try in local environment with serial comilation it is always working. Unfortunately we have to use in the final build an external setup that we cannot force to operate in a serial way. We could provide a fix to you if you like.

**Comment by alexcojocaru** [comment]
Okay, that makes sense now.
I can fix this in the couple of days; if you need a fix sooner and you can fix it yourself, contributions are very welcome.

**Comment by HighstreetHerbert** [comment]
Thanks for fast response. A fix in a couple of day would be good for us. As snapshot verison also ok. At the moment we are in development phase. But there is a requirement to use release plugins in later project phases .. that is Jan 2020 for us. So there is the question if this could be part of a release till this date? Contributing could be an option for later. We need to think about.

**Comment by alexcojocaru** [comment]
This is going to take longer than a couple of days to implement; to avoid having separate builds download the same artifact multiple times in parallel (which, given the large size of the artifact, could create bandwidth issues), I have to implement an inter-process sync mechanism for the plugin resolution. It's not simple, but I already have a plan for how to do it.
Will post here once it's implemented.
A quick fix you could use until I implement this properly is to install the artifact in the maven repo of the build server manually; then all builds will find it there (and not have to download it).

**Comment by HighstreetHerbert** [comment]
We are not blocked here and really happy with the functionality of the plugin. If the build of a component fails we starting the build again. This is Ok for the moment. Thanks a lot for your support.

**Comment by alexcojocaru** [comment]
A quick update on this:
Most of the implementation is done, I need to clean up the code and do some more testing. Will add another comment once I make some more significant progress.

**Comment by HighstreetHerbert** [comment]
Good timing .. just this week start to provide to a gerrit repo and just saw this problem. So support is highly welcome. Thanks a lot.

**Comment by alexcojocaru** [comment]
I have fixed this issue and I am releasing a new version of the plugin - `6.16`. Let me know if it works for you; if by any chance it does not, set the logLevel to DEBUG in the plugin config to get more details on what the plugin is doing.

**Comment by HighstreetHerbert** [comment]
Ok, thanks a lot. I will start testing today.

**Comment by alexcojocaru** [comment]
Do you have any updates on this? If it works well for you, I would like to close this issue.

**Comment by HighstreetHerbert** [comment]
I have not yet the result. The test is still pending. They like to verify this today .. that I can answer this week. Thanks for remining me and excuse me for the delay.

**Comment by HighstreetHerbert** [comment]
Hi alexcojocaru ... thanks again for providing this feature. The test was successfully done.
