### ISSUE TITLE
How to fix elasticsearch node startup taking too long?

### ISSUE THREAD

**Issue by Ltadrian** [alexcojocaru/elasticsearch-maven-plugin#106]
We have multiple builds using this library on this same jenkins server and all of our builds get stuck on the following step for 5-10 minutes and fail all of our builds:
[INFO] Using Elasticsearch [0] configuration: com.github.alexcojocaru.mojo.elasticsearch.v2.InstanceConfiguration@41e5038a[id=0,baseDir=/tmp/build_dir/target/elasticsearch0,httpPort=9200,transportPort=9300,pathData=<null>,pathLogs=<null>,settings=<null>]
[INFO] Elasticsearch[0]: Executing command '[chmod, 755, bin/elasticsearch-plugin]' in directory '/tmp/build_dir/target/elasticsearch0'
[INFO] Elasticsearch[0]: The process finished with exit code 0
[INFO] Elasticsearch[0]: Executing command '[sed, -i, -e, 1s:.*:#!/usr/bin/env bash:, bin/elasticsearch-plugin]' in directory '/tmp/build_dir/target/elasticsearch0'
[INFO] Elasticsearch[0]: The process finished with exit code 0
[INFO] Elasticsearch[0]: Executing command '[bin/elasticsearch-plugin, list]' in directory '/tmp/build_dir/target/elasticsearch0'
[INFO] Elasticsearch[0]: The process finished with exit code 0
[INFO] Elasticsearch[0]: Executing command '[chmod, 755, bin/elasticsearch]' in directory '/tmp/build_dir/target/elasticsearch0'
[INFO] Elasticsearch[0]: The process finished with exit code 0
[INFO] Elasticsearch[0]: Executing command '[sed, -i, -e, 1s:.*:#!/usr/bin/env bash:, bin/elasticsearch]' in directory '/tmp/build_dir/target/elasticsearch0'
[INFO] Elasticsearch[0]: The process finished with exit code 0
[INFO] Elasticsearch[0]: Executing command '[bin/elasticsearch, -p, pid, -Ecluster.name=HibernateSearchCluster, -Ehttp.port=9200, -Etransport.tcp.port=9300, -Ehttp.cors.enabled=true]' in directory '/tmp/build_dir/target/elasticsearch0'

How should I be configuring this plugin for different repositories needing to build their own elasticsearch nodes on the same jenkins host?

**Comment by alexcojocaru** [comment]
There could be several reasons for this:
- multiple ES servers trying to bind to the same http and transport ports
- https://github.com/alexcojocaru/elasticsearch-maven-plugin/issues/105, which I fixed recently, but which could have introduced a bug

If it's the former, it could be solved easily by configuring different ports in the ES plugin config and in the ES client config.

**Comment by Ltadrian** [comment]
I tried switching the http and tcp ports and running two builds at once but both failed with the same error message after 3 minutes:
[ERROR] Failed to execute goal com.github.alexcojocaru:elasticsearch-maven-plugin:6.13:runforked (start-elasticsearch) on project location-management-services: Condition returned by method "waitToStartInstance" in class com.github.alexcojocaru.mojo.elasticsearch.v2.client.Monitor was not fulfilled within 120 seconds. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.alexcojocaru:elasticsearch-maven-plugin:6.13:runforked (start-elasticsearch) on project location-management-services: Condition returned by method "waitToStartInstance" in class com.github.alexcojocaru.mojo.elasticsearch.v2.client.Monitor was not fulfilled within 120 seconds.

I remember we bumped up the timeout to 120 seconds since that kind of helped at one point but still not working as smoothly. I looked at the bug you mentioned and I'm not really seeing the same error message so I'm not entirely sure if this still applies. Any clue?

**Comment by alexcojocaru** [comment]
To rule out the 2nd potential root cause: that feature (https://github.com/alexcojocaru/elasticsearch-maven-plugin/issues/105) was added in the latest release (i.e. 6.16); could you switch to 6.15 and try again? Note that 6.15 could break builds running at the same time on the same machine if the ES artifact was not already downloaded and installed in the local maven repo, see that defect for details on it.

If that doesn't solve your problem:
- set a clusterName unique per build
- you've already said that you use different http and transport ports per build
- set the logLevel to DEBUG in the plugin config (see the readme for details on that)

If that still doesn't solve the problem send me the build log with the debug level on.

**Comment by Ltadrian** [comment]
Thanks for the response alex. so we had to shift quickly shift gears yesterday and went to hosting our own es nodes internally for our build process. If that ends up not working out we'll come back to this plugin. Thanks again for this plugin, its a good one
