### ISSUE TITLE
Add support for downloading from a url protected by basic authentication

### ISSUE THREAD

**Issue by jonfreedman** [alexcojocaru/elasticsearch-maven-plugin#109]
As per [StackOverflow](https://stackoverflow.com/questions/46259498/fileutils-copyurltofile-basicauthenication) this currently does not work.
```xml
<configuration>
    <downloadUrl>https://${username}:${password}@my_private_repository/elasticsearch-downloads/%s</downloadUrl>
</configuration>
```
I think additional config parameters for username/password would be most appropriate

**Comment by alexcojocaru** [comment]
Thanks for the pull request, I am going to look at it and integrate it later today.

**Comment by jonfreedman** [comment]
It would be great if you could release a new version of the plugin with this change

**Comment by alexcojocaru** [comment]
All done, v6.17
