### ISSUE TITLE
Add elasticsearch oss for 6.8.10

### ISSUE THREAD

**Issue by royteeuwen** [alexcojocaru/elasticsearch-maven-plugin#114]
Is it possible to provide the elasticsearch oss for 6.8.10? I don't immediately see where I could do it myself, else I would make the PR

**Comment by alexcojocaru** [comment]
One of the plugin properties is the ES `flavour` (see the README for details). It's OSS by default.

To use ES v6.8.10, you'd need a plugin config such as the following - this is copied from the README, there are XML comments in the example there (and here) which should help you with the config:
```
<plugin>
    <groupId>com.github.alexcojocaru</groupId>
    <artifactId>elasticsearch-maven-plugin</artifactId>
    <!--
        THE PLUGIN VERSION; FOR THE LIST OF AVAILABLE VERSIONS, SEE
        https://github.com/alexcojocaru/elasticsearch-maven-plugin/releases
    -->
    <version>6.17</version>
    <configuration>
        <!-- THE ELASTICSEARCH VERSION; REPLACE WITH THE VERSION YOU NEED -->
        <version>6.8.0</version>
    </configuration>
    <executions>
       ...
    </executions>
</plugin>
```

**Comment by royteeuwen** [comment]
Hey,

That is indeed what we have configured, but the maven logging that I get is that it first tries to download mvnrepo/com/github/alexcojocaru/elasticsearch-oss-6.8.10.zip but that it doesn't find that so it falls back to a hard install from the artifacts.elastic.co websites

Seeing as our ci/cd is behind a firewall and we can only access artifacts through nexus, I was wondering if it is you who puts it in com/github/alexcojocaru/... on public maven repo or can we maybe specify a url ourselves in the configuration section ?

**Comment by alexcojocaru** [comment]
Yes; there are 2 ways:
* use the `downloadUrl` attribute of the plugin to download the ES from a specific location
* before running your build, install the ES package in the mvn repo using mvn install:install-file

These options are described in the README and have been discussed in various issues.

**Comment by royteeuwen** [comment]
Sorry for being so ignorant, should have read the docs better. I just looked at the examples / checked out the project. Thanks for being patient ;)
