### ISSUE TITLE
Using ${build.directory} in the configPath

### ISSUE THREAD

**Issue by angelcervera** [alexcojocaru/elasticsearch-maven-plugin#12]
I am using the plugin inside of a submodule project, so I need to specify the config folder using one of the maven properties.
Something like this:
```
				<configuration>
					<clusterName>idx-integrationtest-cluster</clusterName>
					<tcpPort>9399</tcpPort>
					<httpPort>9299</httpPort>
					<configPath>${build.directory}/src/test/resources/es_config</configPath>
				</configuration>
```
But looks like  **_${build.directory}_** is not supported inside of the configPath.
How to do it?

Regards.

**Comment by alexcojocaru** [comment]
This is more of a Maven question, for Maven is responsible for expanding the property and pass the config path to the plugin. Have you tried using _${project.build.directory}_ instead?

**Comment by angelcervera** [comment]
I'm sorry. My fault. I wanted access to the root of the maven module, so it is ${project.basedir}
The plugin is working, no my brain.

Thanks.
