### ISSUE TITLE
Cannot download and start 8.x

### ISSUE THREAD

**Issue by ChrisSamo632** [alexcojocaru/elasticsearch-maven-plugin#140]
`transport.tcp.port` is no longer a valid setting (should be `transport.port`).

Elasticsearch 8.x is also "secure by default" with TLS certificates generated for use on startup and a generated password for the `elastic` (and other built-in) user(s). This may need to be handled differently when starting up the instance(s).

**Comment by ChrisSamo632** [comment]
May also be worth addressing the fact that OSS releases stopped after 7.10.2 as well (I.e. only `default` instead)

**Comment by alexcojocaru** [comment]
Thanks for reporting that, Chris. I will look into fixing those issues soon.

**Comment by alexcojocaru** [comment]
I doubt it's worth getting this project to work with the latest ES version. There is not much info on the *oss* version, I wonder how you found out that version 7.10.2 was the last one to have an *oss* flavour. If that is accurate, it's been more than a year since that version was released, and no one else raised this issue. In other words, I wonder if this maven plugin is still used by anyone else.

**Comment by ChrisSamo632** [comment]
You can see the release history for elasticsearch-oss at https://www.elastic.co/downloads/past-releases#elasticsearch-oss

Elasticsearch combined their release artifacts into https://www.elastic.co/downloads/past-releases#elasticsearch a while ago, the difference now being what xpack licence (if any) one chooses to use when starting the elasticsearch instance(s) - no xpack effectively being the oss version

I know this plugin works with the latest 7.17.0 version of elasticsearch (just use the "default" flavour and optionally add xpack settings for the startup) as it's used in apache/nifi for integration tests (https://github.com/apache/nifi/blob/main/nifi-nar-bundles/nifi-elasticsearch-bundle/nifi-elasticsearch-client-service/pom.xml), which is where I was hoping to use the same for 8 0.0 to prove compatibility - https://issues.apache.org/jira/browse/NIFI-9678 (the integration tests in nifi main are currently set to use 7.10.2 due to the oss versioning, but only because I didn't want to add another -default only profile into the linked pom, I have successfully tested it with newer versions though)

**Comment by ChrisSamo632** [comment]
Interestingly this plugin is one of those suggested in an Elastic issue that's been open for a while about documenting options for (external) application developers to integration test with elasticsearch - https://github.com/elastic/elasticsearch/issues/55258

But as you say, I guess not many have been using it with more recent versions of elasticsearch

**Comment by alexcojocaru** [comment]
I have started working on making it work with ES 8. Removing the *flavour* option and renaming the *transport.tcp.port* property were simple to fix; the https/security changes are more difficult to adapt too. The Zen discovery was completely redone in ES, which might have broken the multi-instance configuration of the plugin - will look into that too.

**Comment by alexcojocaru** [comment]
All done; just finished pushing the latest version 6.20 to sonatype.

**Comment by ChrisSamo632** [comment]
> All done; just finished pushing the latest version 6.20 to sonatype.

That's great, I'll try to make use of it in the near future and will raise any further issues separately
