### ISSUE TITLE
Unable to call POST _refresh

### ISSUE THREAD

**Issue by ChrisSamo632** [alexcojocaru/elasticsearch-maven-plugin#142]
Specifying `POST:_refresh:{}` in a `set.script` or a `script.json` with:

```json
[
  {
    "method": "POST",
    "path": "_refresh",
    "payload": {}
  }
]
```

Fails with an error message from Elasticsearch saying that a POST to `_refresh` cannot contain a payload, which suggests that the plugin is trying to perform the request with a payload (even if empty).

The plugin documentation suggests setting the `payload` to `{}` for a `POST _refresh` call, but this doesn't appear to work in the latest versions.

**Comment by alexcojocaru** [comment]
Fixed; I am about to release a newer version which includes the fix for this.

**Comment by alexcojocaru** [comment]
I am putting the release on hold for the next little while; there's a build error on Windows which I need to sort out first.

**Comment by alexcojocaru** [comment]
You can use the latest release; it contains all the fixes.

**Comment by ChrisSamo632** [comment]
> You can use the latest release; it contains all the fixes.

Does it need pushing to [Maven Central](https://search.maven.org/artifact/com.github.alexcojocaru/elasticsearch-maven-plugin) (or similar) still, looks like the latest there is still 6.19 (although I was able to obtain 6.20 from [Central](https://repo.maven.apache.org/maven2/com/github/alexcojocaru/elasticsearch-maven-plugin/6.20/elasticsearch-maven-plugin-6.20.pom) previously)?

**Comment by ChrisSamo632** [comment]
> > You can use the latest release; it contains all the fixes.
> 
> Does it need pushing to [Maven Central](https://search.maven.org/artifact/com.github.alexcojocaru/elasticsearch-maven-plugin) (or similar) still, looks like the latest there is still 6.19 (although I was able to obtain 6.20 from [Central](https://repo.maven.apache.org/maven2/com/github/alexcojocaru/elasticsearch-maven-plugin/6.20/elasticsearch-maven-plugin-6.20.pom) previously)?

Realised it's version `6.22` (not `6.21`, presumably abandoned due to the mentioned Windows build issues?) and these are available via https://oss.sonatype.org/#nexus-search;quick~elasticsearch-maven-plugin 👍

**Comment by alexcojocaru** [comment]
It's in [Maven Central](https://search.maven.org/artifact/com.github.alexcojocaru/elasticsearch-maven-plugin/6.22/maven-plugin) too now. It's the first time that the maven release was successful and the artifacts were not in Maven Central within a few hours.

You presumed correctly: I aborted version 6.21 after tagging, but before publishing, once I saw the Windows test results.
