### ISSUE TITLE
Could not resolve artifact with coordinates org.elasticsearch.distribution.zip:elasticsearch:zip:6.8.0

### ISSUE THREAD

**Issue by dudu3000** [alexcojocaru/elasticsearch-maven-plugin#143]
Hi there. I'm getting this error when I try to compile my project:
```
com.github.alexcojocaru.mojo.elasticsearch.v2.configuration.ResolutionException: Could not resolve artifact with coordinates org.elasticsearch.distribution.zip:elasticsearch:zip:6.8.0
```
I tried to compile it using Java `11.0.12` and also using Java `1.8.0_202` on Windows10, using Maven.
Is this a problem or it can be related to my setup? (I've noticed a closed issue #111  about this for `6.13` version, but the person who raised the problem hasn't provided further details and issue was closed)

PS: It fails when using `mvn install`. For `mvn package` works fine

**Comment by dudu3000** [comment]
This is the configuration in `pom.xml`:
```

            <plugin>
                <groupId>com.github.alexcojocaru</groupId>
                <artifactId>elasticsearch-maven-plugin</artifactId>
                <version>5.3</version>
                <configuration>
                    <clusterName>testCluster</clusterName>
                    <transportPort>9500</transportPort>
                    <httpPort>9400</httpPort>
                    <version>${elasticsearch.version}</version>
                </configuration>
                <executions>
                    <execution>
                        <id>start-elasticsearch</id>
                        <phase>pre-integration-test</phase>
                        <goals>
                            <goal>runforked</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>stop-elasticsearch</id>
                        <phase>post-integration-test</phase>
                        <goals>
                            <goal>stop</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```

**Comment by alexcojocaru** [comment]
The plugin version you're trying to use - `5.3` - is a very old version. My gut feeling is that it doesn't support ES 6.8.0 .

Is there anything stopping you from using a newer version? While older plugin versions don't support newer ES versions, the opposite is true; even the latest plugin version supports ES 5.0 through 8.0 .

See this for all available plugin versions: https://search.maven.org/artifact/com.github.alexcojocaru/elasticsearch-maven-plugin

**Comment by dudu3000** [comment]
Hi, thank you for fast reply. I put ES 6.8.11 (after checking mvn2 repo) and it works. It seems like ES 6.8.0 is not on the repository, but somehow it was or something because the tool I'm working on used to work and I checked the file and there were no changes to the file.

Shortly, I checked on mvn repository for the closest ES version to 6.8.0 and used that one. Now all good.

**Comment by alexcojocaru** [comment]
One thing to note: the version on line 4 in the pom.xml above is the plugin version; the version on line 9 is the Elasticsearch server version. There is nothing forcing you to use the same version number on both lines; on the contrary, e.g. set the plugin version to the latest (because why not) and the Elasticsearch server version to whatever you want that to be.
