### ISSUE TITLE
Problem running plugin on java 17

### ISSUE THREAD

**Issue by marcingasior** [alexcojocaru/elasticsearch-maven-plugin#148]
Hello,

I created a sample project on spring initializer and added following section for elastic plugin.
I'm running windows 10 and amazon correto 17.0.4.9.1
`
<properties>
		<java.version>17</java.version>
		<elasticsearch-maven-plugin.version>6.23</elasticsearch-maven-plugin.version>
		<elastic-search.version>8.3.3</elastic-search.version>
	</properties>
<plugin>
				<groupId>com.github.alexcojocaru</groupId>
				<artifactId>elasticsearch-maven-plugin</artifactId>
				<version>${elasticsearch-maven-plugin.version}</version>
				<configuration>
					
					<skip>${skipITs}</skip>
					<clusterName>wsintegrationtest</clusterName>
					<transportPort>9398</transportPort>
					<httpPort>9298</httpPort>
					<version>${elastic-search.version}</version>
					<timeout>300</timeout>

					
					
					<logLevel>DISABLED</logLevel>
				</configuration>
				<executions>
					
					<execution>
						<id>start-elasticsearch</id>
						<phase>pre-integration-test</phase>
						<goals>
							<goal>runforked</goal>
						</goals>
					</execution>
					<execution>
						<id>stop-elasticsearch</id>
						<phase>post-integration-test</phase>
						<goals>
							<goal>stop</goal>
						</goals>
					</execution>
				</executions>
			</plugin>

`

When trying to run mvn clean install than it throws with following:
`
[ERROR] Failed to execute goal com.github.alexcojocaru:elasticsearch-maven-plugin:6.22:runforked (start-elasticsearch) on project demo: Elasticsearch [0]: Cannot execute command '[cmd, /c, bin\elasticsearch-plugin, remove, "[0.058s]
[warning][jni,resolve] Re-registering of platform native method: java.lang.PanwHooks.NativeMethodEntry(Ljava/lang/Object;ILjava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Lj
ava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)V from code in a different classloader"]' in directory 'C:\dev\dplus\demo\target\elasticsearch0'
[ERROR] Output:
[ERROR] [0.055s][warning][jni,resolve] Re-registering of platform native method: java.lang.PanwHooks.NativeMethodEntry(Ljava/lang/Object;ILjava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljav
a/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)V from code in a different classloader
[ERROR] Error:
[ERROR] warning: ignoring JAVA_HOME=C:\Program Files\Amazon Corretto\jdk17.0.4_9; using bundled JDK 
[ERROR] Exception in thread "main" java.nio.file.InvalidPathException: Illegal char <:> at index 71: [0.058s][warning][jni,resolve] Re-registering of platform native method: java.lang.PanwHooks.NativeMethodEntry(Ljava/lang/Object;IL
java/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)V from code in a different classloader
[ERROR]         at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
[ERROR]         at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
[ERROR]         at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
[ERROR]         at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
[ERROR]         at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:232)
[ERROR]         at java.base/java.nio.file.Path.resolve(Path.java:515)
[ERROR]         at org.elasticsearch.plugins.cli.RemovePluginAction.checkCanRemove(RemovePluginAction.java:123)
[ERROR]         at org.elasticsearch.plugins.cli.RemovePluginAction.execute(RemovePluginAction.java:80)
[ERROR]         at org.elasticsearch.plugins.cli.RemovePluginCommand.execute(RemovePluginCommand.java:43)
[ERROR]         at org.elasticsearch.common.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:54)
[ERROR]         at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:85)
[ERROR]         at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:94)
[ERROR]         at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:85)
[ERROR]         at org.elasticsearch.cli.Command.main(Command.java:50)
[ERROR]         at org.elasticsearch.launcher.CliToolLauncher.main(CliToolLauncher.java:64): Process exited with an error: 1 (Exit value: 1)
[ERROR] -> [Help 1]

`
Can you please help with this?

**Comment by alexcojocaru** [comment]
I had no problem starting ES 8.3.3 with two flavours of Java 17.0.4 : Zulu and Correto

Here's the output from `java -version`
```
openjdk version "17.0.4" 2022-07-19 LTS
OpenJDK Runtime Environment Corretto-17.0.4.8.1 (build 17.0.4+8-LTS)
OpenJDK 64-Bit Server VM Corretto-17.0.4.8.1 (build 17.0.4+8-LTS, mixed mode, sharing)
```

And this is my pom file, for reference:
```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.alexalecu</groupId>
  <artifactId>es-test</artifactId>
  <packaging>jar</packaging>
  <version>1.0-SNAPSHOT</version>
  <name>es-test</name>
  <url>http://maven.apache.org</url>
  <repositories>
    <repository>
      <snapshots>
        <enabled>false</enabled>
      </snapshots>
      <id>central</id>
      <name>Maven Repository Switchboard</name>
      <url>http://repo1.maven.org/maven2</url>
    </repository>
  </repositories>
  <dependencies>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>3.8.1</version>
      <scope>test</scope>
    </dependency>
  </dependencies>
  <properties>
    <maven.compiler.source>1.8</maven.compiler.source>
    <maven.compiler.target>1.8</maven.compiler.target>
  </properties>
  <build>
      <plugins>
            <plugin>
                <groupId>com.github.alexcojocaru</groupId>
                <artifactId>elasticsearch-maven-plugin</artifactId>
                <version>6.23</version>
                <configuration>
                    <version>8.3.3</version>
                    <clusterName>test</clusterName>
                    <transportPort>9300</transportPort>
                    <httpPort>9200</httpPort>
                    <setAwait>true</setAwait>
                </configuration>
                <executions>
                    <execution>
                        <id>start-elasticsearch</id>
                        <phase>pre-integration-test</phase>
                        <goals>
                            <goal>runforked</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>stop-elasticsearch</id>
                        <phase>post-integration-test</phase>
                        <goals>
                            <goal>stop</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
      </plugins>
  </build>
</project>
```

I hope this helps.

**Comment by SimoneCafiero** [comment]
Hey @alexcojocaru,
I faced the same issue as @marcingasior.

Have you verified it in Microsoft Windows 10? My version is 10.0.19043 anyway.

Just to say that it looks to have no issue with MacOs or Linux.

**Comment by marcingasior** [comment]
Thanks @alexcojocaru, for checking that. I checked the same on my mac and under ubuntu running wsl, and it worked fine in both.
It seems there is an issue with Windows only. I believe it might be the issue with elastic itself.

Let me know your thoughts, please. 
Thanks,
Marcin

**Comment by SimoneCafiero** [comment]
Hello @alexcojocaru ,

did you have the chance to replicate the scenario?

Thanks,

Simone

**Comment by alexcojocaru** [comment]
No, not yet. I will look into that in the next few days.

**Comment by SimoneCafiero** [comment]
Perfect, thanks.

**Comment by alexcojocaru** [comment]
It worked for me. Here are the configuration details:
* same _pom.xml_ as in [the 2nd comment on this thread](https://github.com/alexcojocaru/elasticsearch-maven-plugin/issues/148#issuecomment-1242638770), with a single change: the ES version is 8.4.3 instead of 8.3.3
* Windows 10
* Java 17
  ```
  openjdk version "17.0.4.1" 2022-08-12
  OpenJDK Runtime Environment Temurin-17.0.4.1+1 (build 17.0.4.1+1)
  OpenJDK 64-Bit Server VM Temurin-17.0.4.1+1 (build 17.0.4.1+1, mixed mode, sharing)
  ```

**Comment by marcingasior** [comment]
Thanks for help Alex.
I believe it might be due to Palo Alto scanner, which is doing something strange with jdk.
I raised the issue with our internal networking/security team.

Cheers,
Marcin
