### ISSUE TITLE
Plugin seems to be there, but I get Connection refused

### ISSUE THREAD

**Issue by sweissascension** [alexcojocaru/elasticsearch-maven-plugin#149]
This is in a jenkins pipeline and after upgrading to elastic 8.4.1 it was unable to find an instance of elastic search.  Before apparently we could pass in null for the host and it would work, but the ElasticsearchClient seems to require a local instance of elastic running.  So we are trying this.
Without the plugin the error indicated there was no elastic search instance to connect to.  Now we get the "Refused."  So I think it works.  Am just using the standard plugin config.  host in localhost and protocol is http.

`
<plugin>
                <groupId>com.github.alexcojocaru</groupId>
                <artifactId>elasticsearch-maven-plugin</artifactId>
                
                <version>6.23</version>
                <configuration>
                    
                    <version>8.4.1</version>
                    <clusterName>test</clusterName>
                    <transportPort>9300</transportPort>
                    <httpPort>9200</httpPort>
                    <autoCreateIndex>false</autoCreateIndex>
                </configuration>
                <executions>
                    
                    <execution>
                        <id>start-elasticsearch</id>
                        <phase>pre-integration-test</phase>
                        <goals>
                            <goal>runforked</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>stop-elasticsearch</id>
                        <phase>post-integration-test</phase>
                        <goals>
                            <goal>stop</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
`

Have tried with and without index creation.  
   : actuatorRestClient elasticSearchHost: localhost 
 : elasticsearchClient 
  : create ElasticsearchTemplate
 : RuntimeException
GenericWebApplicationContext   : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'getInfoController' defined in file ...: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'esSearchService' defined in file ....EsSearchService.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'elasticsearchTemplate' defined in class path resource ...EsConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.data.elasticsearch.client.elc.ElasticsearchTemplate]: Factory method 'elasticsearchTemplate' threw exception; nested exception is java.lang.RuntimeException: java.net.ConnectException: Connection refused

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
: Application run failed

**Comment by alexcojocaru** [comment]
I am not following your ask; it would help if you clarify a few things for me:

> after upgrading to elastic 8.4.1 it was unable to find an instance of elastic search

Who was unable to find an instance of ES? Are you referring to the integration tests in your app?

>  we could pass in null for the ost

What is "ost"? I am not familiar with the acronym.

> ElasticsearchClient seems to require a local instance of elastic running

The ES server is started by the plugin on the local machine, as a separate process.

> Without the plugin the error indicated there was no elastic search instance to connect to. Now we get the "Refused."

What do you mean by "without the plugin" ?

**Comment by alexcojocaru** [comment]
FWIW I have tested the plugin with ES 8.4.2 a while back and it worked as expected.

**Comment by sweissascension** [comment]
code is 
RestClientBuilder builder = RestClient.builder(
                            new HttpHost(elasticSearchHost, 9200, "http"))
                    .setRequestConfigCallback(
                            requestConfigBuilder -> requestConfigBuilder
                                    .setConnectTimeout(10_000)
                                    .setSocketTimeout(10_000));
            return builder.build();
 elasticSearchHost = localhost
 result is java.lang.RuntimeException: java.net.ConnectException: Connection refused
