### ISSUE TITLE
Compatibility of licenses

### ISSUE THREAD

**Issue by rahulmohang** [alexcojocaru/elasticsearch-maven-plugin#151]
Hi,

The file, 'https://github.com/alexcojocaru/elasticsearch-maven-plugin/blob/master/src/main/java/com/github/alexcojocaru/mojo/elasticsearch/v2/util/ArchiveUtil.java' is licensed under LGPL-2.1-or-later. Do you think that this could be incompatible with the license Apache-2.0 of the project?

**Comment by alexcojocaru** [comment]
Nice catch; as far as I can tell, it's incompatible - the LGPL license is more restrictive than the Apache one.
Since that's the only file covered by the LGPL license and since it's very simple, I am going to rewrite it from scratch.

**Comment by rahulmohang** [comment]
Thank you.

**Comment by alexcojocaru** [comment]
It's fixed in version 6.26, which should be available in Maven Central shortly.

**Comment by rahulmohang** [comment]
Thank you.

**Comment by dummyelastic** [comment]
@alexcojocaru  is it possible to make it work for gradle also or if there is anything already existing for gradle?
