### ISSUE TITLE
Similiar Plugin for OpenSearch?

### ISSUE THREAD

**Issue by multikoop** [alexcojocaru/elasticsearch-maven-plugin#152]
Hi!

great work! I still could not find out, so trying to get an answer here.

Is there a similar plugin for opensearch?  What would be the best practice? or just using testcontainers with opensearch e.g. ?

Thx
Andreas

**Comment by alexcojocaru** [comment]
Testcontainers is your best bet most probably, if the build environment has docker/container support.

I cannot tell if there is a similar plugin for opensearch, or if this plugin works with it. Opensearch was created as a fork of ES, and it could have diverged enough to make it incompatible with this plugin.

**Comment by multikoop** [comment]
@alexcojocaru ok, thanks for confirming!
