### ISSUE TITLE
resolve ES for Mac M1?

### ISSUE THREAD

**Issue by liujoey** [alexcojocaru/elasticsearch-maven-plugin#156]
Hi, I'm trying to use this plugin on a macos M1, the plugin solve the download url as  `elasticsearch-8.8.1-darwin-x86_64.tar.gz`, but the correct version should be `elasticsearch-8.8.1-darwin-aarch64.tar.gz`

**Comment by liujoey** [comment]
`org.apache.commons.lang3.SystemUtils.OS_ARCH` should give you the correct arch name, so in `ElasticsearchArtifact.getArtifactClassifier` function, we can use this value instead of hard code the `darwin-x86_64`

**Comment by alexcojocaru** [comment]
Fixed in version 6.27
