### ISSUE TITLE
wait Indefinitely

### ISSUE THREAD

**Issue by winnettjohnston** [alexcojocaru/elasticsearch-maven-plugin#20]
Hi Alex,

Thank you for the plugin!

I am trying to pass the -DwaitIndefinitely but it is not working. What am i missing. 

mvn clean verify -DwaitIndefinitely

**Comment by alexcojocaru** [comment]
You need to start ES using the "run" goal; there is no support for the waitIndefinitely argument.
Check out this section on the project main page: "Run Elasticsearch node"

Alex

**Comment by winnettjohnston** [comment]
Hi alex, i have added the code below to my pom.xml and am running the mvn clean verify. It is the ES node is not running. Am i doing something incorrect?

Thanks again 
`  <plugin>
        <groupId>com.github.alexcojocaru</groupId>
        <artifactId>elasticsearch-maven-plugin</artifactId>
        
        <version>2.0</version>
        <configuration>
            <clusterName>test</clusterName>
            <tcpPort>9300</tcpPort>
            <httpPort>9200</httpPort>
        </configuration>
        <executions>
            
            <execution>
                <id>start-elasticsearch</id>
                <phase>pre-integration-test</phase>
                <goals>
                    <goal>run</goal>
                </goals>
            </execution>
        </executions>
        <dependencies>
            <dependency>
                <groupId>org.elasticsearch</groupId>
                <artifactId>elasticsearch</artifactId>
                
                <version>2.0.0</version>
            </dependency>
        </dependencies>
    </plugin>`

**Comment by alexcojocaru** [comment]
That looks correct. Let me try that myself and I will post back once I know more.

**Comment by alexcojocaru** [comment]
I created an empty maven project with:
`mvn archetype:generate -DgroupId=com.github.alexcojocaru -DartifactId=elasticsearch-maven-plugin-test -DarchetypeArtifactId=maven-archetype-quickstart -DinteractiveMode=false`
then changed the pom.xml to https://gist.github.com/alexcojocaru/97d44965964ab170f41b2462c9e4bbb8.

Running `$ mvn clean verify` starts the ES server and waits indefinitely, until I press CTRL+C to stop the process.

**Comment by winnettjohnston** [comment]
I have confirmed this works as described. thank you for your help :) 

And thanks again for the plugin
