### ISSUE TITLE
I can start plugin blocking execution

### ISSUE THREAD

**Issue by aakhmerov** [alexcojocaru/elasticsearch-maven-plugin#31]
**Use-Case**

when I develop integration tests and want to debug them, I want to run plugin in blocking manner in order not to have to restart ES all the time, or run full maven `clean verify` cycle. 

**AT**
* given 
  * plugin has a `run` mojo 
* when 
  * I execute `run` goal
* then
  * ES instance is started with configuration values specified for the plugin 
  * ES instance is blocking and waits for requests

**Comment by aakhmerov** [comment]
Hi @alexcojocaru, 

could you do a review please. Would be also perfect if you could release a minor or patch version with this change, assuming you accept PR of course. 

Cheers,
Askar.

**Comment by alexcojocaru** [comment]
Does this plugin parameter: `setAwait` (see https://github.com/alexcojocaru/elasticsearch-maven-plugin for details) provide support for your use case?

**Comment by aakhmerov** [comment]
Hey, @alexcojocaru in that case I would have to configure extra profile for blocking execution, right? With `run` goal I could just do `mvn -DskipTests com.github.alexcojocaru:elasticsearch-maven-plugin:5.4-SNAPSHOT:run`. If use `setAwait` then I would add fixed profile `dev` or something and just run `mvn -DskipTests -Pdev clean verify`. 

So the answer is yes, but I would love to do it without extra profiles in my pom :)

Cheers,
Askar

**Comment by alexcojocaru** [comment]
Not necessarily.

There are two ways to control the setAwait behavior:

* use a maven property which you set by default to false, and you override that as needed in the pom.xml and on the cmd line
* add `-Des.setAwait=true` to the command line, eg. `mvn clean verify -Des.setAwait=true`

**Comment by aakhmerov** [comment]
@alexcojocaru,

thanks, that would work for me.
