### ISSUE TITLE
Override Xms, Xmx

### ISSUE THREAD

**Issue by yflement** [alexcojocaru/elasticsearch-maven-plugin#36]
Is it possible to override the default xms and xmx arguments of Elasticsearch?

> [INFO ][o.e.n.Node               ] JVM arguments [-Xms2g, -Xmx2g,...]

**Comment by alexcojocaru** [comment]
Yes, it is possible. Use the *pathConf* parameter to tell ES to use an external directory as config directory, and you can overwrite the JVM options in the jvm.options file. The caveat is that you need an elasticsearch.yml file in there too, and probably also a log properties file, if you have non default configuration.

**Comment by yflement** [comment]
Thanks that works!
