### ISSUE TITLE
Do not fail when a plugin has already been installed

### ISSUE THREAD

**Issue by dadoonet** [alexcojocaru/elasticsearch-maven-plugin#41]
When I add a plugin with its file URL like `file://path/to/target/myplugin.zip` and start again the same `mvn install` command, it fails because the plugin already exists.

Tested with 5.4.2:

```
[INFO] Elasticsearch[0]: Executing command '[bin/elasticsearch-plugin, install, --batch, file:///Users/dpilato/Documents/Elasticsearch/dev/elasticsearch-beyonder/target/integration-tests/plugins/x-pack-5.4.2.zip]' in directory '/Users/dpilato/Documents/Elasticsearch/dev/elasticsearch-beyonder/target/elasticsearch0'
-> Downloading file:///Users/dpilato/Documents/Elasticsearch/dev/elasticsearch-beyonder/target/integration-tests/plugins/x-pack-5.4.2.zip
[=================================================] 100%   
ERROR: plugin directory [/Users/dpilato/Documents/Elasticsearch/dev/elasticsearch-beyonder/target/elasticsearch0/plugins/x-pack] already exists; if you need to update the plugin, uninstall it first using command 'remove x-pack'
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 9.137 s
[INFO] Finished at: 2017-06-21T14:18:09+02:00
[INFO] Final Memory: 30M/325M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.alexcojocaru:elasticsearch-maven-plugin:5.7:runforked (start-elasticsearch) on project elasticsearch-beyonder: Elasticsearch [0]: Cannot execute command '[bin/elasticsearch-plugin, install, --batch, file:///Users/dpilato/Documents/Elasticsearch/dev/elasticsearch-beyonder/target/integration-tests/plugins/x-pack-5.4.2.zip]' in directory '/Users/dpilato/Documents/Elasticsearch/dev/elasticsearch-beyonder/target/elasticsearch0': Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

IMHO this should not fail the build or at least we need an option to ignore that failure.

WDYT?

**Comment by alexcojocaru** [comment]
The option to ignore that specific installation error does not sound good to me; just because one might update the plugin attributes in the pom file, then run `mvn install` to save time, and end up with an unexpected [ES] environment.

By option, did you mean a plugin attribute (just like `esJavaOpts`) ? That would also be dangerous, for one might update the plugin version number and not the ignoreInstallationError attribute, and end up with an unexpected ES env.

Instead, I would rather run a command to uninstall the plugin before installing it; the problem with this though is that we don't know the plugin name to use in the `elasticsearch-plugin remove` command.

What do you think about removing the whole `plugins` directory before installing the requested plugins?

**Comment by alexcojocaru** [comment]
@dadoonet any thoughts on my previous comment (more specifically, what I am proposing at the end of it)?

**Comment by dadoonet** [comment]
Sorry. Still on my TODO to evaluate this and update my PR. :D

**Comment by alexcojocaru** [comment]
I can implement this myself in the near future (ie. next few weeks). I was just wondering what you think about the last option (removing the whole `plugins` directory) - in my mind, that's the desired behavior.

**Comment by dadoonet** [comment]
> The option to ignore that specific installation error does not sound good to me; just because one might update the plugin attributes in the pom file, then run mvn install to save time, and end up with an unexpected [ES] environment.

Sure. But for that specific use case which is probably less than 1% of the time spent on running `mvn install`, I'd expect people running `mvn clean install`. Well, anytime I'm changing the `pom.xml` like this (changing a dep), I'm running a `clean`.

> When you said "at least we need an option to ignore that failure", does option mean a plugin attribute (just like esJavaOpts) ? That would also be dangerous, for one might update the plugin version number and not the ignoreInstallationError attribute, and end up with an unexpected ES env.

Yeah. That's what I meant. Same  answer as the previous one. I think that if I'm activating an option like `doNotFailOnExistingPluginEvenIfIKnowItCanBehaveBadly: true` I understand what I'm doing.
 
> Instead, I would rather run a command to uninstall the plugin before installing it; the problem with this though is that we don't know the plugin name to use in the elasticsearch-plugin remove command.

Yeah. That's indeed bad as you can't use the same command line you used to install. I don't think you can solve this issue without giving a list of plugin names to be uninstalled which is too complicated (or too much) IMO.

> What do you think about removing the whole plugins directory before installing the requested plugins? That is doable.

Totally doable indeed. What I don't like is that it will consume time again and again by default, by downloading plugins from internet. May be that should be optional as well?

----

My opinion is that we should have:

* Add an option `fail_on_existing_plugin`, defaults to `true`.

Or

* Empty entirely the `plugins` dir before installing plugins.

The later is easier, safer but will take more time when we will run tests. (Think about ingest-attachment or ingest-geoip plugins which are "big" ZIP files).
The former will be faster but might have some side effects as you said.

My 2 cents.

**Comment by alexcojocaru** [comment]
I've added a configuration step which removes the `plugins` directory before installing the required plugins (the change hasn't been pushed yet). What I found during testing is that the `plugins` directory is always empty after the ES installation is copied to the target directory, therefore the extra step I've added is superfluous.
Can you tell me how to duplicate the issue you're having, and what your specific config is?

**Comment by dadoonet** [comment]
Here is what I'm doing (running that from https://github.com/dadoonet/elasticsearch-beyonder):

## Step 1

```sh
mvn clean install -Pes-xpack
```

## Step 2

As #42 is not fixed yet, this is not working. I either CTRL+C or wait for it to fail.

## Step 3

Run again but this time without using `clean`:

```sh
mvn install -Pes-xpack
```

This is failing with:

```
[INFO] --- elasticsearch-maven-plugin:5.7:runforked (start-elasticsearch) @ elasticsearch-beyonder ---
[INFO] Using Elasticsearch [0] configuration: com.github.alexcojocaru.mojo.elasticsearch.v2.InstanceConfiguration@7885776b[id=0,baseDir=/Users/dpilato/Documents/Elasticsearch/dev/elasticsearch-beyonder/target/elasticsearch0,httpPort=9400,transportPort=9500,pathData=<null>,pathLogs=<null>]
[DEBUG] Resolving ElasticsearchArtifact[org.elasticsearch.distribution.zip:elasticsearch:zip:5.5.0]
[DEBUG] Resolving artifact org.elasticsearch.distribution.zip:elasticsearch:zip:5.5.0 from [elastic-download-service (https://artifacts.elastic.co/maven/, default, releases), oss-snapshots (https://oss.sonatype.org/content/repositories/snapshots/, default, snapshots), central (https://repo.maven.apache.org/maven2, default, releases)]
[DEBUG] Resolved artifact org.elasticsearch.distribution.zip:elasticsearch:zip:5.5.0 to /Users/dpilato/.m2/repository/org/elasticsearch/distribution/zip/elasticsearch/5.5.0/elasticsearch-5.5.0.zip from elastic-download-service (https://artifacts.elastic.co/maven/, default, releases)
[DEBUG] Using environment: null
[INFO] Elasticsearch[0]: Executing command '[chmod, 755, bin/elasticsearch-plugin]' in directory '/Users/dpilato/Documents/Elasticsearch/dev/elasticsearch-beyonder/target/elasticsearch0'
[INFO] Elasticsearch[0]: The process finished with exit code 0
[INFO] Installing plugin 'file:///Users/dpilato/Documents/Elasticsearch/dev/elasticsearch-beyonder/target/integration-tests/plugins/x-pack-5.5.0.zip' with options 'null'
[DEBUG] Using environment: null
[INFO] Elasticsearch[0]: Executing command '[bin/elasticsearch-plugin, install, --batch, file:///Users/dpilato/Documents/Elasticsearch/dev/elasticsearch-beyonder/target/integration-tests/plugins/x-pack-5.5.0.zip]' in directory '/Users/dpilato/Documents/Elasticsearch/dev/elasticsearch-beyonder/target/elasticsearch0'
-> Downloading file:///Users/dpilato/Documents/Elasticsearch/dev/elasticsearch-beyonder/target/integration-tests/plugins/x-pack-5.5.0.zip
[=================================================] 100%   
ERROR: plugin directory [/Users/dpilato/Documents/Elasticsearch/dev/elasticsearch-beyonder/target/elasticsearch0/plugins/x-pack] already exists; if you need to update the plugin, uninstall it first using command 'remove x-pack'
```

Let me know if you need more info.

**Comment by alexcojocaru** [comment]
I cannot follow the steps - there's a failure in the first one (`mvn clean install -Pes-xpack`):
```
[ERROR] Failed to execute goal on project elasticsearch-beyonder: Could not resolve dependencies for project fr.pilato.elasticsearch:elasticsearch-beyonder:jar:5.2-SNAPSHOT: Could not find artifact org.elasticsearch.client:x-pack-transport:jar:5.5.0 in internal-repository```
I checked and the artifact is not in maven central (search.maven.org).

**Comment by dadoonet** [comment]
@alexcojocaru Are you using any enterprise Nexus like repository manager?

Asking that because the `x-pack` plugin should be available from:

```
        <repository>
            <id>elastic-download-service</id>
            <name>Elastic Download Service</name>
            <url>https://artifacts.elastic.co/maven/</url>
            <releases>
                <enabled>true</enabled>
            </releases>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
```

Which is in `pom.xml`.

**Comment by alexcojocaru** [comment]
Yes I am. I will add the ES repo to my settings.

**Comment by alexcojocaru** [comment]
And I was able to reproduce the issue. I will provide a fix for it shortly.

**Comment by alexcojocaru** [comment]
Removing the `plugins` directory will not solve the problem. You can try it out locally by manually removing the said directory before running `mvn install -Pes-xpack`.

The reason being that the x-pack plugin also installs something in the `bin` directory, so when the ES maven plugin tries to install the plugin (during `mvn install -Pes-xpack`), it runs into an error:
```
Exception in thread "main" java.nio.file.FileAlreadyExistsException: /Users/alex/pub/temp/elasticsearch-beyonder/target/elasticsearch0/bin/x-pack
```

Looks like removing the `plugins` directory will not work for all plugins. And I don't want to write any plugin specific code in the ES maven plugin (ie. to remove the bin/x-pack directory).

Any thoughts?

**Comment by dadoonet** [comment]
There is one possibility I think which requires a bit more work.

You could run:

```sh
bin/elasticsearch-plugin list
```

Then collect the list of installed plugins if any and for each one call:

```sh
bin/elasticsearch-plugin remove [plugin_name]
```

Might be the cleanest way to support this.

Another option would be by changing a bit the following:

```xml
            <plugins>
                <plugin>
                    <uri>analysis-icu</uri>
                <plugin>
                <plugin>
                    <uri>https://github.com/alexcojocaru/plugin.zip</uri>
                    <esJavaOpts>-Djavax.net.ssl.trustStore=/home/alex/trustStore.jks</esJavaOpts>
                <plugin>
                <plugin>
                    <uri>file:///home/alex/foo.zip</uri>
                <plugin>
            </plugins>
```

to

```xml
            <plugins>
                <plugin>
                    <uri>analysis-icu</uri>
                <plugin>
                <plugin>
                    <name>my-plugin-1</name>
                    <uri>https://github.com/alexcojocaru/plugin.zip</uri>
                    <esJavaOpts>-Djavax.net.ssl.trustStore=/home/alex/trustStore.jks</esJavaOpts>
                <plugin>
                <plugin>
                    <name>my-plugin-2</name>
                    <uri>file:///home/alex/foo.zip</uri>
                <plugin>
            </plugins>
```

Where `name` is optional and defaults to `uri`. In most cases, people won't need that if they want to install standard plugins like:

```xml
                <plugin>
                    <uri>analysis-icu</uri>
                <plugin>
```

WDYT?

**Comment by alexcojocaru** [comment]
I thought about the second option, and I did not like it. The first one thought is more elegant, I will try to implement it.

**Comment by alexcojocaru** [comment]
The latest version (5.9) contains the fix for the plugin problem. I tested it thoroughly with your project and it works as expected. Let me know if you find any further issues.

**Comment by dadoonet** [comment]
Awesome. I'll test it hopefully tomorrow.

Let's close this issue as you fixed it.
