### ISSUE TITLE
Document how to contribute and run tests

### ISSUE THREAD

**Issue by dadoonet** [alexcojocaru/elasticsearch-maven-plugin#43]
Hey

I'm on my way to submit a PR for #42 but I have hard time to understand how to run the test I added to test the new feature I added.
So I'm running for now a `mvn clean install` every time but it's far from being optimal as I'm spending most of the time running the other integration tests.

Could you document how to create tests (well, I copy and paste for now so I should be good) but give some tricks on how to actually run a single test?

Also, everything you put in `src/it` is preprocessed by Groovy if I understand correctly. Is there a best practice to write a `pom.xml` example (and a java test) which you can easily run from the IDE?

Best!

**Comment by alexcojocaru** [comment]
Added a new section to the README file to describe how the integration tests work.

**Comment by dadoonet** [comment]
Awesome. Thanks!
