### ISSUE TITLE
Frequent process Termination

### ISSUE THREAD

**Issue by trprasad** [alexcojocaru/elasticsearch-maven-plugin#44]
Hi, 
I've configure plugin as 
```
            <plugin>
                <groupId>com.github.alexcojocaru</groupId>
                <artifactId>elasticsearch-maven-plugin</artifactId>
                <version>5.9</version>
                <configuration>
                    <clusterName>${elasticsearch.clustername}</clusterName>
                    <transportPort>${elasticsearch.tcp.port}</transportPort>
                    <httpPort>${elasticsearch.http.port}</httpPort>
                    <pathConf>${qa.config.dir}/elasticsearch-config</pathConf>
                    <version>5.5.1</version>
                    <timeout>120</timeout>
                    <autoCreateIndex>false</autoCreateIndex>
                    <plugins>
                        <plugin>
                            <uri>analysis-icu</uri>
                        </plugin>
                        <plugin>
                            <uri>file:///${qa.config.dir}/elasticsearch-plugins/analyzed-queries/analyzed-queries-${elasticsearch.version}.0.zip</uri>
                        </plugin>
                    </plugins>
                </configuration>
                <executions>
                    <execution>
                        <id>start-elasticsearch</id>
                        <phase>pre-integration-test</phase>
                        <goals>
                            <goal>runforked</goal>
                        </goals>
                        <configuration>
                            <pathInitScript>${elasticsearch.loadscript}</pathInitScript>
                            <skip>${skip.elasticsearch}</skip>
                        </configuration>
                    </execution>
                    <execution>
                        <id>stop-elasticsearch</id>
                        <phase>post-integration-test</phase>
                        <goals>
                            <goal>stop</goal>
                        </goals>
                        <configuration>
                            <skip>${skip.elasticsearch}</skip>
                        </configuration>
                    </execution>
                </executions>
                <dependencies>
                    <dependency>
                        <groupId>org.elasticsearch</groupId>
                        <artifactId>elasticsearch</artifactId>
                        <version>${elasticsearch.version}</version>
                    </dependency>
                </dependencies>
            </plugin>
```
But while execution, I keep getting failures while executing **load scripts**

```
[ERROR] Failed to execute goal com.github.alexcojocaru:elasticsearch-maven-plugin:5.9:runforked (start-elasticsearch) on project ls-search-qa-features: Execution start-elasticsearch of goal com.github.alexcojocaru:elasticsearch-maven-plugin:5.9:runforked failed: Cannot execute command PUT:company:{"settings":{"analysis":{"char_filter":{"extract_id":{"type":"pattern_replace","pattern":"^.*?\\s?([\\S]+)\\s*$","replacement":"$1"},"add_start_stop_tokens":
....
....
.....
 java.net.SocketTimeoutException: Read timed out -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :ls-search-qa-features
[INFO] Apache ActiveMQ 5.10.0 (localhost, ID:UX000954-TPL-A-61745-1502096948112-0:1) is shutting down
[INFO] Stopping the Elasticsearch process at application shutdown ...
[INFO] Connector tcp://127.0.0.1:61616 stopped
[INFO] ... the Elasticsearch process has stopped. Exit code: 1
```

Although, this is happening intermittently, one common thing is, this always fails during load script (`<pathInitScript>${elasticsearch.loadscript}</pathInitScript>`) execution.

Could you please take a look?

**Comment by alexcojocaru** [comment]
Could you post a more complete plugin output?
You could also set the `logLevel` to `DEBUG` to get more information.

**Comment by trprasad** [comment]
Sure, I've already enabled `DEBUG` this morning, as soon as I get error again, I'll post it here.
Thanks for looking into problem.

**Comment by alexcojocaru** [comment]
Apologies about the delay.

I started ES using the plugin and tried to create the index using your settings, but it failed (because I don't have your custom plugin installed):
```
{
    "error": {
        "caused_by": {
            "reason": "/test/elasticsearch-maven-plugin-test/target/elasticsearch0/config/synonyms/syn_qtglobalsynonyms.txt (No such file or directory)",
            "type": "file_not_found_exception"
        },
        "reason": "IOException while reading synonyms_path_path: /test/elasticsearch-maven-plugin-test/target/elasticsearch0/config/synonyms/syn_qtglobalsynonyms.txt",
        "root_cause": [
            {
                "reason": "IOException while reading synonyms_path_path: /test/elasticsearch-maven-plugin-test/target/elasticsearch0/config/synonyms/syn_qtglobalsynonyms.txt",
                "type": "illegal_argument_exception"
            }
        ],
        "type": "illegal_argument_exception"
    },
    "status": 400
}
```

What you could do to troubleshoot this issue further is to:
- set up a simple maven project which uses the ES maven plugin, set the `setAwait` attribute to true to have the process block after ES starts (see the project I attached for an example)
- run `mvn verify`, which would start ES and block the process
- create the index via a curl command (eg. `curl -XPUT localhost:9205/company '..jsonHere'`)

If the PUT is successful, then there's a plugin issue. But I am afraid I cannot look into it, since I don't have the synonyms file and your custom plugin.
If the PUT is unsuccessful, let me know - in that case, the plugin does not report the errors correctly and I should be able to fix that.

[elasticsearch-maven-plugin-test.zip](https://github.com/alexcojocaru/elasticsearch-maven-plugin/files/1218904/elasticsearch-maven-plugin-test.zip)

**Comment by trprasad** [comment]
Hi again,

Thanks for your response, I tried your zip & then creating index etc, it worked.. what I was saying is, it does work in my integrated environment too.. just that at time (3 time in 10 attempts), it fails with reported error.

I 'm guessing that some step is killing ES running in background & hence in the end I get error "java.net.SocketTimeoutException: Read timed out", and this happens only during execution of load script. It contains lot of lines and failure occurs executing random line.. I'm not sure even how to get to bottom of it.

As for custom plugin, you already have commented it out which is OK, it won't affect your test any way. As for synonym file in the index you're trying, here is what you can do,
replace `"synonyms_path":"synonyms/syn_qtglobalsynonyms.txt"` in the index json with `"synonyms": ["dog, pet, animal"]` . You should be able to proceed.. 

Meanwhile, even I'll see if I can give you some more information.. somehow.. :(

**Comment by alexcojocaru** [comment]
The plugin does not execute the script until ES has fully started - in debug mode, you'll see some logs about a monitor waiting for ES to start. Only after ES has started, the plugin will move on to the next step, which in your case is executing the script.

ES dying while the script is being executed is one option (although I don't find it probable).
Another option is that the script takes very long to execute, in which case the HTTP client will error out with "Read timed out" message.

The HTTP client configuration is in  ElasticsearchClient (https://github.com/alexcojocaru/elasticsearch-maven-plugin/blob/master/src/main/java/com/github/alexcojocaru/mojo/elasticsearch/v2/client/ElasticsearchClient.java). I am referring to this specifically:
```java
        cm.setDefaultSocketConfig(SocketConfig.custom()
                .setSoTimeout(1000)
                .setSoLinger(0)
                .setTcpNoDelay(true)
                .build());
```
If ES takes more than 1 sec to execute the script, the HTTP client will error out. It's 1 sec because it was not designed for very large init scripts.

Can you check out the code, change the SoTimeout to 5000 and rebuild the plugin (`mvn clean install`)? That would install version 5.10-SNAPSHOT in your local repo. If that works without issues, let me know and I can make the change (or you can create a pull request).

**Comment by trprasad** [comment]
Sure, I'll.. it may take a while before I post information back to you.

Thanks again

**Comment by alexcojocaru** [comment]
That's strange - it looks like the `pid` file created by ES is left behind on your machine. I don't have a Windows machine handy, once I get access to one I will test.

In the meanwhile, please use this snapshot version I built with the Socket timeout set to 5 seconds. You need to install it in your local mvn repo and update the plugin version to 5.10-SNAPSHOT in your project.
[elasticsearch-maven-plugin-5.10-SNAPSHOT.jar.zip](https://github.com/alexcojocaru/elasticsearch-maven-plugin/files/1226268/elasticsearch-maven-plugin-5.10-SNAPSHOT.jar.zip)

**Comment by trprasad** [comment]
This is definitely looking promising, tried several times, no failure yet.. I think raising `setSoTimeout(5000)` is doing the trick. I'll keep an eye for longer time.

Thank you very much for looking into this problem.

**Comment by trprasad** [comment]
Sure, I'll...

Yes, I see a `pid` file in directory:

1. `elasticsearch-maven-plugin/target/it/runforked-auto-create-index-false/target/elasticsearch0/`
![image](https://user-images.githubusercontent.com/17176875/29405330-8634bd2c-8335-11e7-8f3f-b49b71a76be1.png)

2. `elasticsearch-maven-plugin/target/it/runforked-defaults/target/elasticsearch0/`
![image](https://user-images.githubusercontent.com/17176875/29405444-d6e6ddea-8335-11e7-9f4e-7f0a02608b8e.png)

3. `elasticsearch-maven-plugin/target/it/runforked-multi/target/elasticsearch0/`
![image](https://user-images.githubusercontent.com/17176875/29405536-1090ee0a-8336-11e7-8724-b7e3791d63f3.png)

4. `elasticsearch-maven-plugin/target/it/runforked-with-init-script/target/elasticsearch0/`
![image](https://user-images.githubusercontent.com/17176875/29405600-364913b6-8336-11e7-832a-bdb79fe25366.png)

5. `elasticsearch-maven-plugin/target/it/runforked-with-path-conf/target/elasticsearch0/`
![image](https://user-images.githubusercontent.com/17176875/29405646-61f5d094-8336-11e7-870e-e6c51e34302d.png)

6. `elasticsearch-maven-plugin/target/it/runforked-with-path-scripts/target/elasticsearch0/`
![image](https://user-images.githubusercontent.com/17176875/29405681-7e04f198-8336-11e7-99c8-385e21ebe012.png)

7. `elasticsearch-maven-plugin/target/it/runforked-with-plugins/target/elasticsearch0/`
![image](https://user-images.githubusercontent.com/17176875/29405710-9a2daa36-8336-11e7-9347-419bda4a5bcd.png)

Looks like almost every directory.. that means a common step somewhere... Hope this helps!

**Comment by alexcojocaru** [comment]
Thanks for the confirmation. The `pid` file should not be there after the ES instance shuts down. I will take a look at this issue asap.

**Comment by trprasad** [comment]
Hi Alex,

Do you know when next release (`5.10`) is planned with `setSoTimeout(5000)`? I'm holding up for this :)

Thanks

**Comment by alexcojocaru** [comment]
As soon as you confirm the change fixes the issue, I will push to the main branch and build a release.

**Comment by alexcojocaru** [comment]
I went ahead with the fix and released the plugin. The version number is 5.10

**Comment by trprasad** [comment]
Hi @alexcojocaru ,
I'm getting this ` java.net.SocketTimeoutException: Read timed out` messages again, is it possible to set that  `setSoTimeout(5000)` from `5000` to `10000`?

**Comment by alexcojocaru** [comment]
I would rather make the so timeout configurable.  Give me a day or so to update the plugin and release a new version.

**Comment by trprasad** [comment]
That's wonderful, sure. Thanks again Alex.

**Comment by alexcojocaru** [comment]
This change is going to take a few more days, sorry about that.

**Comment by trprasad** [comment]
Sure, no problem Alex. Thanks again!

**Comment by alexcojocaru** [comment]
It's done. I added the `clientSocketTimeout` option - see the readme for details and let me know if it works for you.

**Comment by trprasad** [comment]
Thanks Alex, I've tested, and it's working.

Thanks again for quick fix.
