### ISSUE TITLE
How to set Elasticsearch version.

### ISSUE THREAD

**Issue by EricGregMiller** [alexcojocaru/elasticsearch-maven-plugin#46]
According to the README `<version>` is used to set Elasticsearch version. Default "5.0.0". However, setting version to 5.0.0 causes a maven error.
`[ERROR] Plugin com.github.alexcojocaru:elasticsearch-maven-plugin:5.0.0 or one of its dependencies could not be resolved: Failure to find com.github.alexcojocaru:elasticsearch-maven-plugin:jar:5.0.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]`

That message makes it sound like <version> sets the elasticsearch-maven-plugin version, not the Elasticsearch version. Indeed, values of 5.5 or 5.9 work just fine even though there currently is no version 5.9 of Elasticsearch.

On the other hand, no matter what I set in `<version>` I always see Elasticsearch 5.0.0 launched. I want to launch ES 5.5.0. How do I do that?

**Comment by EricGregMiller** [comment]
Nvm. The `<version>` set in the main section is the plugin version. The `<version>` set in the configuration section is the ES version. It would _really_ help to add this to the example. It's possible there are other users as clueless as me, who still think of maven as kind of a magic black box.

**Comment by EricGregMiller** [comment]
[README.zip](https://github.com/alexcojocaru/elasticsearch-maven-plugin/files/1235864/README.zip)
Here is my README change with ES version example.

**Comment by alexcojocaru** [comment]
Thanks for the patch. It has been applied to the master branch.
