### ISSUE TITLE
The JVM Shutdownhook seems not to be working on Windows

### ISSUE THREAD

**Issue by cgoeller** [alexcojocaru/elasticsearch-maven-plugin#52]
When the stop goal is not executed, (due to a failing test), the ES instance is still running. Consecutive executions of maven will fail.

The log output shows:

```
[INFO] Stopping the Elasticsearch process at application shutdown ...
[INFO] ... the Elasticsearch process has stopped. Exit code: 1
```

On Linux it works:
```
[INFO] Stopping the Elasticsearch process at application shutdown ...
[INFO] ... the Elasticsearch process has stopped. Exit code: 143
```

Environment:
```
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T17:41:47+01:00)
Maven home: c:\Apps\apache-maven-3.3.9
Java version: 1.8.0_112, vendor: Oracle Corporation
Java home: c:\Apps\Java\jdk8_112_64\jre
Default locale: de_DE, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "dos"
```

Plugin Version 6.0
ES Version 5.6.3

**Comment by alexcojocaru** [comment]
Thanks for reporting this, Christian.
I started looking at this and I'll keep you posted.

**Comment by cgoeller** [comment]
Thank you very much. 
I tried to investigate the problem. It guess that the actual ES process is different from the process (the batch file) which is launched by the plugin.

**Comment by alexcojocaru** [comment]
Just a quick update, Christian.
I fixed the bug on Windows, but I am going to need a little more time to refactor the patch (the code is pretty ugly at the moment) - hopefully by end of day I will build a new release with the fix.

**Comment by cgoeller** [comment]
Thanks for the update. Please let me know if I should test the fixed plugin.

**Comment by alexcojocaru** [comment]
There's a new release (6.1) with the fix for process termination on Windows. It works for me - check it out and let me know if it works for you either.

**Comment by cgoeller** [comment]
Your fix works perfectly. Thank you very much. It saves me a lot of time.
I will close this issue now.
