### ISSUE TITLE
Test creating snapshots, need to configure path.repo

### ISSUE THREAD

**Issue by jettro** [alexcojocaru/elasticsearch-maven-plugin#54]
Hi, looking to find if it is possible to set the path.repo parameter. Can I set it somewhere or do I need to provide a custom config file?

**Comment by dadoonet** [comment]
I'd use pathConf option and provide there a custom elasticsearch.yml and the log4j config file.

**Comment by alexcojocaru** [comment]
I agree with @dadoonet ; instead of adding a large number of config options to this plugin, to match the ES config options, I would rather provide a custom ES config via the `pathConf`option.

**Comment by jettro** [comment]
I understand, looking for a way to pass the path from maven though. I would not like it to hardcode the path of the repository as the maven build should be able to run everywhere

**Comment by jettro** [comment]
Hmm, it turns out elasticsearch path.repo does not need to be an absolute path any longer. So providing an elasticsearch.yml with path.repo: backups seems to work just fine.

**Comment by alexcojocaru** [comment]
good news
