### ISSUE TITLE
ElasticSearch stopping after Init script execution

### ISSUE THREAD

**Issue by manjirinamjoshi** [alexcojocaru/elasticsearch-maven-plugin#58]
Hello,
I am new at using this plugin, so my apologies if this is a stupid question.

What I am trying to do is, run the elasticsearch instance and then run my application that will connect to this instance. But, when I run -  "mvn elasticsearch:runforked". It starts, runs the Init script and then stops. 

Instead I want to keep it running after the Init script.

[INFO] The Elasticsearch instance has started
[INFO] The Elasticsearch cluster has started
[INFO] Sending PUT request to http://localhost:9200/test/ with entity '{ "mappings":{"default":{ "properties":{ "myField":{"type":"keyword"}}}}}'
[2018-02-26T16:21:58,423][INFO ][o.e.c.m.MetaDataCreateIndexService] [aswHGsc] [test] creating index, cause [api], templates [], shards [5]/[1], mappings [default]
[INFO] Sending PUT request to http://localhost:9200/test/default/1 with entity '{ "myField ":"hello world"}'
[2018-02-26T16:21:58,692][INFO ][o.e.c.m.MetaDataMappingService] [aswHGsc] [test/tKNrCWV3RLu8ypMUPqL5XQ] update_mapping [default]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10.795 s
[INFO] Finished at: 2018-02-26T16:21:58-08:00
[INFO] Final Memory: 18M/310M
[INFO] ------------------------------------------------------------------------
[INFO] Stopping the Elasticsearch process at application shutdown ...
[INFO] ... the Elasticsearch process has stopped. Exit code: 143

Thank you

Sincerely,
Manjiri

**Comment by alexcojocaru** [comment]
Have a look at the `setAwait` flag.

**Comment by manjirinamjoshi** [comment]
That did the charm ! Thanks a lot !
