### ISSUE TITLE
Elasticsearch version 2 unable to start instance

### ISSUE THREAD

**Issue by manjirinamjoshi** [alexcojocaru/elasticsearch-maven-plugin#61]
Hello,

Unfortunately, our prod env is running elastic search version 2.4.1. So, I am trying to use version 2 of this plugin.

But, when I try - mvn elasticsearch:start it doesnt seem to load the Init script and also, doesnt seem to start the elasticsearch instance.

IRV-MNAMJOSH-7D:mtd mnamjoshi$ mvn elasticsearch:start
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building java-metadata 0.0.2-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- elasticsearch-maven-plugin:2.0:start (default-cli) @ java-metadata ---
log4j:WARN No appenders could be found for logger (org.elasticsearch.node).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.882 s
[INFO] Finished at: 2018-05-24T22:26:05-07:00
[INFO] Final Memory: 22M/309M
[INFO] ------------------------------------------------------------------------
IRV-MNAMJOSH-7D:mtd mnamjoshi

Following is the snippet from my pom.xml -

<plugin>
    					<groupId>com.github.alexcojocaru</groupId>
    					<artifactId>elasticsearch-maven-plugin</artifactId>
    					
    					<version>2.0</version>
    					
    					<configuration>
        					
        					<version>2.0.0</version>
        					<clusterName>mtd</clusterName>
        					<transportPort>9300</transportPort>
        					<httpPort>9200</httpPort>
        					<tcpPort>9300</tcpPort>
        					<setAwait>true</setAwait>
        					<pathInitScript>src/test/resources/elasticsearch/Init.script</pathInitScript>
    					</configuration>
    					<dependencies>
    						
							<dependency>
    							<groupId>org.slf4j</groupId>
    							<artifactId>slf4j-log4j12</artifactId>
    							<version>1.7.25</version>
							</dependency>
    					</dependencies>
    					<executions>
        					
        					<execution>
            					<id>start-elasticsearch</id>
            					<phase>pre-integration-test</phase>
            					<goals>
                					<goal>runforked</goal>
            					</goals>
        					</execution>
        					<execution>
            					<id>stop-elasticsearch</id>
            					<phase>post-integration-test</phase>
            					<goals>
                					<goal>stop</goal>
            					</goals>
        					</execution>
    					</executions>
					</plugin>

Thank you 

Sincerely,
Manjiri

**Comment by alexcojocaru** [comment]
Sorry about the delay in replying, I thought I have done that already.
It's not working because you are  using the v5+ configuration. Here is the documentation for the 2.x branch: https://github.com/alexcojocaru/elasticsearch-maven-plugin/tree/elasticsearch-2.x, check out the plugin config and goals (eg. `load`, `run`).

**Comment by manjirinamjoshi** [comment]
Thank you for the pointer, I will try it out.

**Comment by alexcojocaru** [comment]
I am going to close this issue; feel free to reopen if the doc is wrong or not clear.
