### ISSUE TITLE
java.io.IOException: An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by alex-semenyuk** [alexcojocaru/elasticsearch-maven-plugin#62]
I got the following, when run mvn verify

```
[2018-05-30T14:28:24,065][WARN ][o.e.h.n.Netty4HttpServerTransport] [h3Pu-H5] caught exception while handling client http traffic, closing connection [id: 0x172478f4, L:/0:0:0:0:0:0:0:1:9400 - R:/0:0:0:0:0:0:0:1:52160]
java.io.IOException: An existing connection was forcibly closed by the remote host
```

Than it proceed and execute all required operations, but would like to avoid this exception. 

Plugin in pom

            <plugin>
                <groupId>com.github.alexcojocaru</groupId>
                <artifactId>elasticsearch-maven-plugin</artifactId>
                <version>6.5</version>
                <configuration>
                    <clusterName>testCluster</clusterName>
                    <transportPort>9500</transportPort>
                    <timeout>5000</timeout>
                    <httpPort>9400</httpPort>
                    <version>5.4.0</version>
                    <pathInitScript>src/test/resources/elasticsearch/Init.script</pathInitScript>
                </configuration>
                <executions>
                    <execution>
                        <id>start-elasticsearch</id>
                        <phase>process-test-classes</phase>
                        <goals>
                            <goal>runforked</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>stop-elasticsearch</id>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>stop</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

**Comment by alexcojocaru** [comment]
Tried your pom config with a new project locally and haven't seen any such warning.
What you're seeing may be due to one of these ES clients aborting the connection:
- the monitor in the ES plugin (which keeps track of the ES server state)
- the init script executor in the ES plugin (unlikely since, from what you're saying, everything seems to be working fine)
- the test code

If I read the warning correctly, it's a transport protocol error and the ES plugin uses only the HTTP protocol to talk to the server. Double check the test code and make sure the ES client shuts down gracefully at the end of your tests.

**Comment by alex-semenyuk** [comment]
It is happened before executing test code 

More details:

```
2018-06-02T22:38:39,151][INFO ][o.e.n.Node               ] [uXZxjOY] started
[DEBUG] Response with status code 200 and content: {  "name" : "uXZxjOY",  "cluster_name" : "test",  "cluster_uuid" : "0CIrKlwVRuyCaK_J3Z04RQ",  "version" : {    "number" : "6.2.4",    "build_hash" : "ccec39f",    "build_date" : "2018-04-12T20:37:28.497551Z",    "build_snapshot" : false,    "lucene_version" : "7.2.1",    "minimum_wire_compatibility_version" : "5.6.0",    "minimum_index_compatibility_version" : "5.0.0"  },  "tagline" : "You Know, for Search"}
[2018-06-02T22:38:39,583][WARN ][o.e.h.n.Netty4HttpServerTransport] [uXZxjOY] caught exception while handling client http traffic, closing con
java.io.IOException: An existing connection was forcibly closed by the remote host
        at sun.nio.ch.SocketDispatcher.read0(Native Method) ~[?:?]
	at sun.nio.ch.SocketDispatcher.read(Unknown Source) ~[?:?]
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(Unknown Source) ~[?:?]
	at sun.nio.ch.IOUtil.read(Unknown Source) ~[?:?]
	at sun.nio.ch.SocketChannelImpl.read(Unknown Source) ~[?:?]
	at io.netty.buffer.PooledHeapByteBuf.setBytes(PooledHeapByteBuf.java:261) ~[netty-buffer-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1106) ~[netty-buffer-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:343) ~[netty-transport-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123) [netty-transport-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645) [netty-transport-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:545) [netty-transport-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499) [netty-transport-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459) [netty-transport-4.1.16.Final.jar:4.1.16.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-common-4.1.16.Final.jar:4.1.16.Final]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
```

**Comment by alexcojocaru** [comment]
Cannot say what's going on there; there is nothing in the stack trace to link it to any of the plugin classes.

**Comment by alexcojocaru** [comment]
Unless you provide more details which show that there's a problem in the src code of the plugin, or provide a sample proj to reproduce the problem, I cannot help with this.

**Comment by Goffen** [comment]
I´m also getting this exception.

I have no testcases and using the following xml: 

`            <plugin>
                <groupId>com.github.alexcojocaru</groupId>
                <artifactId>elasticsearch-maven-plugin</artifactId>
                <version>6.10</version>
                <configuration>
                    <version>6.6.1</version>
                    <clusterName>test</clusterName>
                    <transportPort>9300</transportPort>
                    <httpPort>9200</httpPort>
                </configuration>
                <executions>
                    <execution>
                        <id>start-elasticsearch</id>
                        <phase>pre-integration-test</phase>
                        <goals>
                            <goal>runforked</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>stop-elasticsearch</id>
                        <phase>post-integration-test</phase>
                        <goals>
                            <goal>stop</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>`

**Comment by Goffen** [comment]
For each http-request there is one of those stacktraces. All requests gets through and the test can continue but that exception gets logged

**Comment by Goffen** [comment]
"I assume this error is triggered because your http client closed the
connection before reading the response fully." from some ES-dude

**Comment by alexcojocaru** [comment]
Do you want to re-open this issue for me to investigate it?

**Comment by Goffen** [comment]
That would be great. I will help you provide information. 

One interesting thing I´ve found is that I get same exception when I start an elasicsearch server on the side (not from the plugin).

**Comment by aredspider** [comment]
Same issue here

**Comment by alexcojocaru** [comment]
With the pom you posted above, I cannot reproduce the issue on Linux.
I had a closer look at the plugin code which deals with managing the connections to the ES server and made some improvements, but no changes were made to the ES server config. If the issue described here was due to the plugin, it  should not show up any longer. If it's due to another client (ie. you integration tests) not consuming the response (from ES) fully, then it's up to you to fix it.

**Comment by alexcojocaru** [comment]
Forgot to mention that the latest version of the plugin (which I am releasing now) includes the fixes mentioned in the previous comment.
