### ISSUE TITLE
ES v6.3.0 fails to start with "Permission denied" for the x-pack-ml module

### ISSUE THREAD

**Issue by albogdano** [alexcojocaru/elasticsearch-maven-plugin#65]
With the new version of ES there are now 2 different distribution flavors: 
- **"elasticsearch"** (default, with x-pack) and 
- **"elasticsearch-oss"** (OSS only, no x-pack). 

Some people might need to run tests against either of the two flavors, so I suggest you expose the `artifactId` configuration property for specifying which flavor to download. Alternatively, you could have a config flag `isOSSflavor` or something similar.

Also when the default flavor of 6.3.0 is downloaded and started, I get a "Permission denied" exception because the executables inside `elasticsearch0/modules/x-pack` do not have `+x` permissions on them. So we'd have to run an additional command `chmod 755` on the "modules" folder to get the default flavor running.

**Comment by dadoonet** [comment]
I think that in the context of integration testing, using `elasticsearch-oss` is the right thing to do.
The "full version" contains lot of things that are probably not needed in this context?

At least I'd set `isOSSflavor` to `true` by default.

My 2 cents

**Comment by alexcojocaru** [comment]
The way Elasticsearch changes between minor releases is a PITA. For some reason, there is no zip package for 6.3.0, but there is such package for 6.2.0. I will look into modifying the plugin to use the jar package instead.

**Comment by dadoonet** [comment]
The download is here: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-6.3.0.zip

**Comment by alexcojocaru** [comment]
Thanks for the links, @dadoonet .

**Comment by alexcojocaru** [comment]
I am reluctant to use those links in the plugin. That's because the domain name / path on them may change in the future, whereas mvn repository links have a well defined format which does not change.

**Comment by dadoonet** [comment]
I understand but I'm not sure there is any other choice. The fact that zip files were in Maven previously was considered by Elasticsearch team as a bug, not a feature.
Which means that the distribution assemblies won't be available in Maven in the future.
Same is happening with plugins.

**Comment by alexcojocaru** [comment]
This issue has been fixed and I am currently releasing a new version of the plugin (ie. 6.6).

Check out the new parameters: `flavour` and `downloadUrl`, they should hopefully provide enough flexibility to avoid any further breakages in this area.
