### ISSUE TITLE
Permission denied on Travis with ES 6.4

### ISSUE THREAD

**Issue by kizombaDev** [alexcojocaru/elasticsearch-maven-plugin#70]
I am trying to switch from Elasticsearch version 6.2 to 6.4.
However, I now get the following error when launching Elasticsearch 6.4 on Travis:

`[INFO] Installing /tmp/elasticsearch-oss-6.4.0.zip to /home/travis/.m2/repository/com/github/alexcojocaru/elasticsearch-oss/6.4.0/elasticsearch-oss-6.4.0.zip`
`[INFO] Elasticsearch[0]: Executing command '[chmod, 755, bin/elasticsearch-plugin]' in directory '/home/travis/build/kizombaDev/EventStudio/event-common/target/elasticsearch0'`
`[INFO] Elasticsearch[0]: The process finished with exit code 0`
`[INFO] Elasticsearch[0]: Executing command '[sed, -i, -e, 1s:.*:#!/usr/bin/env bash:, bin/elasticsearch-plugin]' in directory '/home/travis/build/kizombaDev/EventStudio/event-common/target/elasticsearch0'`
`[INFO] Elasticsearch[0]: The process finished with exit code 0`
`[INFO] Elasticsearch[0]: Executing command '[bin/elasticsearch-plugin, list]' in directory '/home/travis/build/kizombaDev/EventStudio/event-common/target/elasticsearch0'
bin/elasticsearch-plugin: line 3: bin/elasticsearch-cli: Permission denied`

Everything worked fine with ES 6.2 ...
Am I doing something wrong or is this possibly a bug?

Let me know if you need further information

**Comment by osman** [comment]
this doesnt look to be related to the plugin itself, `elasticsearch-cli` is not executable in `elasticsearch-oss-6.4.0.zip`

**Comment by kizombaDev** [comment]
The problem is that the `elasticsearch-plugins` calls the `elasticsearch-cli` internally and the  `elasticsearch-cli` has no execute permission on linux
The fix makes the `elasticsearch-cli` also executable ...

I created a pull request with the fix: #71 

@alexcojocaru: Is there a plan when the next version will be released?

**Comment by alexcojocaru** [comment]
Thank you for the fix, @kizombaDev . I've just released a newer version (6.8) which includes it.
