### ISSUE TITLE
Build fails on Windows

### ISSUE THREAD

**Issue by rustyx** [alexcojocaru/elasticsearch-maven-plugin#75]
It is impossible to build the plugin on a Windows system:

1. `BootstrapClusterStepTest` fails due to path separator differences (`'\'` vs `'/'`).

2. `taskkill /F` forcibly kills the ES instance and leaves the `pid` file around. Subsequent `isAlive` checks fail.

**Comment by alexcojocaru** [comment]
Fixed.
