### ISSUE TITLE
Add non-daemon/fork mode goal to stay running until manually stopped

### ISSUE THREAD

**Issue by jeffjensen** [alexcojocaru/elasticsearch-maven-plugin#81]
This plugin is fantastic for starting and stopping ES during the build; thank you for it!

Due to the fast lather-rinse-repeat cycle of test creation/modification and app code creation/modification, keeping the server running for developing and manually testing (e.g. running a specific test) would reduce the cycle time.

I would like to use this plugin for that too, keeping the config with one setup for development and automated tests.  Adding an option to manually start the server and stay running until manually stopped (with the stop goal or Ctrl-c the console) would accomplish this; perhaps a "run" goal in addition to "runforked" would work?

**Comment by alexcojocaru** [comment]
Have a look at the `setAwait` parameter. Is that what you're looking for?

**Comment by jeffjensen** [comment]
!@#$ Sorry, I missed it; yes it is!
