### ISSUE TITLE
Not working for Elastic Search Java High Level Rest Client

### ISSUE THREAD

**Issue by ganil89** [alexcojocaru/elasticsearch-maven-plugin#82]
Hi, We were using this dependency for testing Integration test cases. Recently we upgraded from Transport Client to High Level Client. After this migration, this is not working, getting Connection Refused.

So could you support for High Rest Client ?

**Comment by dadoonet** [comment]
As far as I remember I was able to use this plugin with the Rest layer. Could you share the elasticsearch logs and may be your code or a log from your code printing on which host / port you are connecting to?

**Comment by alexcojocaru** [comment]
Can it be that you tried using the transport port to connect the client to the server?

**Comment by alexcojocaru** [comment]
@ganil89 sorry about the delay in replying to this, I was away for a while.
Can you provide a sample project which shows this issue?

**Comment by steghio** [comment]
Hi @ganil89 , could it be that the port you are using is not correct? The transport client uses something like 9300 default and the rest high level client uses 9200 instead and both can be enabled at the same time on Elasticsearch so when switching clients you also need to change port in the config. 

For me connection works:

````
@Configuration
@EnableElasticsearchRepositories(basePackages = "com.example.repository")
public class ElasticsearchConfig {

    private static final Logger LOGGER = LoggerFactory.getLogger(ElasticsearchConfig.class);

    @Value("${elasticsearch.host}")
    private String host;

    @Value("${elasticsearch.port}")
    private int port;

    @Bean(destroyMethod = "close")
    public RestHighLevelClient client() {

        LOGGER.trace("host: {}, port: {}", this.host, this.port);

        final RestHighLevelClient client = new RestHighLevelClient(RestClient.builder(new HttpHost(host, port, "http")));
        return client;
    }

    @Bean
    public ElasticsearchOperations elasticsearchTemplate() {
        return new ElasticsearchRestTemplate(client());
    }

}
````

Hope it helps

**Comment by alexcojocaru** [comment]
Thanks for confirming that it works as expected, Stefano.
I am going to close this issue.
