### ISSUE TITLE
logLevel

### ISSUE THREAD

**Issue by brackxm** [alexcojocaru/elasticsearch-maven-plugin#89]
logLevel is not working for me
plugin version: 6.13
elasticsearch version: 6.6.2

a workaround is to use instanceSettings iso logLevel

**Comment by alexcojocaru** [comment]
Just to be clear, the `logLevel` param controls the log level on the plugin; it has nothing to do with the Elasticsearch configuration. I just tested the plugin with the log level set to `DEBUG` and the execution output quite a few debug messages.
If you still think it's an issue, show me your plugin config.

**Comment by brackxm** [comment]
ok, i misunderstood
