### ISSUE TITLE
Cannot use ES 7.x image with this plugin

### ISSUE THREAD

**Issue by lyle-partsavatar** [alexcojocaru/elasticsearch-maven-plugin#95]
I am unable to download an ES 7.x image using this plugin by setting the <version> tag value to a 7.x value.  It appears the root cause of this is that the plugin is using a format string (or regex) to set the URL where it should download the ES image from, and ElasticSearch changed the URL format starting with version 7.

**Comment by alexcojocaru** [comment]
It works for me; here's the log which shows that ES 7.2.0 was downloaded and installed locally by the plugin
```
[DEBUG] Resolving artifact com.github.alexcojocaru:elasticsearch-oss:tar.gz:darwin-x86_64:7.2.0 from [central (https://repo.maven.apache.org/maven2, default, releases)]
Downloading from central: https://repo.maven.apache.org/maven2/com/github/alexcojocaru/elasticsearch-oss/7.2.0/elasticsearch-oss-7.2.0-darwin-x86_64.tar.gz
[DEBUG] Artifact not found; downloading and installing it
[DEBUG] Downloading https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-oss-7.2.0-darwin-x86_64.tar.gz to /var/folders/x_/shbt7k3x3qj0dtcld828sjbxnb61g8/T/elasticsearch-oss-7.2.0-darwin-x86_64.tar.gz
[DEBUG] Installing /var/folders/x_/shbt7k3x3qj0dtcld828sjbxnb61g8/T/elasticsearch-oss-7.2.0-darwin-x86_64.tar.gz in the local maven repo
[DEBUG] Installing artifact: com.github.alexcojocaru:elasticsearch-oss:tar.gz:darwin-x86_64:7.2.0
```

**Comment by lyle-partsavatar** [comment]
Nevermind, I was using version 6.8 of the plugin as described in the README.md, not the latest version.  Upgrading the plugin to 6.13 fixed the issue.
