### ISSUE TITLE
Add option to clean elasticsearch0 folder at startup

### ISSUE THREAD

**Issue by steghio** [alexcojocaru/elasticsearch-maven-plugin#97]
Hello,

currently the plugin will unpack whatever target release is specified in folder elasticsearch0 under target in the project root.

Subsequent invocations of the verify goal will fail if that folder (more specifically the indexes) is not cleaned. Adding a setup script for example will not run twice in a row, the second time an "Index already exists" error will be thrown.

Since it might not be convenient to always run a clean before a verify, please add an option to perform the cleaning of the local instance when the plugin is setting everything up.

Thanks and cheers

**Comment by alexcojocaru** [comment]
Sounds like a nice improvement, I will look into making it.
In the meanwhile, if you are blocked or annoyed by this, feel free to `rm -r target/elasticsearch0/data` before running `mvn verify` without clean.

**Comment by steghio** [comment]
Yes I do that manually no problem.

I would say if the other PR goes well, I might attempt this change as well

Cheers

**Comment by steghio** [comment]
Hello,

I found out this can be achieved with [Maven clean plugin](https://maven.apache.org/plugins/maven-clean-plugin/) binding the `clean` goal for specific cleanup of `elasticsearch0` folder to `pre-integration-test` phase. Important is to exclude default `excludeDefaultDirectories` cleanup otherwise the full target folder gets cleaned, something like:

````
<plugin>
    <artifactId>maven-clean-plugin</artifactId>
    <version>3.1.0</version>
    <executions>
        <execution>
            <id>cleanup</id>
            <phase>pre-integration-test</phase>
            <goals>
                <goal>clean</goal>
            </goals>
            <configuration>
                <excludeDefaultDirectories>true</excludeDefaultDirectories>
                <filesets>
                    <fileset>
                        <directory>${project.build.directory}/elasticsearch0</directory>
                    </fileset>
                </filesets>
            </configuration>
        </execution>
    </executions>
</plugin>
````

Therefore I think this feature might not be needed in your plugin at all. I will leave this issue open for you to decide, feel free to close if you think this is enough

Cheers

**Comment by alexcojocaru** [comment]
Aren't you overriding and messing up the *clean* plugin config? Will it still work as expected when you run *mvn clean package* for example?

**Comment by alexcojocaru** [comment]
Thanks for confirming and for the details. I am closing this issue now.
